module.exports = {
  LOADING_ON: LOADING_ON,
  LOADING_OFF: LOADING_OFF,
  SET_PROFILE_ONE: SET_PROFILE_ONE,
  SET_PROFILE_TWO: SET_PROFILE_TWO,
  REMOVE_PROFILE_ONE: REMOVE_PROFILE_ONE,
  REMOVE_PROFILE_TWO: REMOVE_PROFILE_TWO
};

const LOADING_ON = 'LOADING_ON';
const LOADING_OFF = 'LOADING_OFF';
const SET_PROFILE_ONE = 'SET_PROFILE_ONE';
const SET_PROFILE_TWO = 'SET_PROFILE_TWO';
const REMOVE_PROFILE_ONE = 'REMOVE_PROFILE_ONE';
const REMOVE_PROFILE_TWO = 'REMOVE_PROFILE_TWO';
